name: Restore Lockfile if Missing

on:
  push:
    branches: [main, feat/admin-panel-skeleton]
  pull_request:
    branches: [main, feat/admin-panel-skeleton]

jobs:
  restore-lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check for lockfile
        id: check_lockfile
        run: |
          if [ ! -f pnpm-lock.yaml ]; then
            echo "Lockfile missing! Restoring from template."
            cp .github/workflows/pnpm-lock.template.yaml pnpm-lock.yaml
          fi
      - name: Commit restored lockfile
        if: steps.check_lockfile.outputs.lockfile_missing == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add pnpm-lock.yaml
          git commit -m 'ci: restore missing pnpm-lock.yaml [skip ci]' || echo "No changes to commit"
          git push || echo "No changes to push" 